name: Create folder test

on:
  push:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: self-hosted
    #container:
    #  image:  myoung34/github-runner:latest

    steps:
    - name: Create Folder
      run: mkdir abel