name: Python CI(selfhost)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    # 這裡使用變數，會自動跑三個獨立的 job
    runs-on: self-hosted
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install python3 and pip in docker
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
  
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        
    - name: Run tests
      run: PYTHONPATH=. pytest -q