name: Pytest CI(selfhost)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install python3 and pip in docker
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
  
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest
        
    - name: Run tests
      run: |
        python3 -m pytest --version
        mkdir /abel

    - name: Verify Python3 Installation
      run: |
        echo "==== 檢查 Python3 執行檔 ===="
        which python3
        python3 --version
    
        echo "==== 檢查 Pip3 執行檔 ===="
        which pip3
        pip3 --version